sudo: required

services:
  - docker

env:
  global:
    CACHE_IMAGE: jhburns/docker-ci-cache

before_script:
  - docker pull $CACHE_IMAGE:latest || true
  - cd ./Assignment1

script:
  - docker build --cache-from $CACHE_IMAGE:latest --tag $CACHE_IMAGE:latest . --target=test

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then docker login -u $REGISTRY_USER -p $REGISTRY_PASS ; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then docker push $CACHE_IMAGE:latest ; fi;
