sudo: required

services:
  - docker

env:
  global:
    CACHE_IMAGE: jhburns/docker-ci-cache

before_script:
  - docker pull $CACHE_IMAGE:latest || true
  - cd ./Assignment1

script:
  - docker build --cache-from $CACHE_IMAGE:latest --tag $CACHE_IMAGE:latest . --target=full

after_success:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  - docker push $CACHE_IMAGE:latest
